### PR TITLE
max14662: Remove module prefix from private variable

### LINKED ISSUE #7: Remove module name from private variable
https://github.com/xil-se/xildebug_sw/blob/b5ef8b66cc7f98fa468062f20203c5f07501058a/app/drivers/max14662.c#L17

### PR DESCRIPTION
**Pull request by kbeckmann**
closes #7

### CODE REVIEW

**Comment by arturo182** [comment]
This works for now, but maybe we should have a static struct per module to keep all private variables, maybe name it `module` or `mod` or similar?

**Comment by kbeckmann** [comment]
> This works for now, but maybe we should have a static struct per module to keep all private variables, maybe name it module or mod or similar?

We could try the Thing we talked about a while ago.

Create a define in each module, e.g. #define MODULE my_module, then have a struct like
```
// in a global include:
#define THIS MODULE##_data

// in each module.c:
#define MODULE my_module
#include "the file above"

static struct {
  uint32_t foo;
  uint32_t bar;
} THIS ;
```

This way, you can easily find each struct in gdb, i.e. `print my_module_data`

**Comment by arturo182** [comment]
I like everything except the name THIS, won't look nice in the code, should be lowercase, `this` is not a keyword in C AFAIK but better not to confuse editors and people. Not sure what else would be better, maybe @EnJens has something

**Comment by arturo182** [comment]
Self could work, module as well

**Comment by kbeckmann** [comment]
Ok, let's go for `self`

**Comment by arturo182** [comment]
Sure, we can always rename pretty easily

**Pull request merged**
