### PR TITLE
main: Fix clock configuration

### PR DESCRIPTION
**Pull request by kbeckmann**
Found this issue when running with USE_FULL_ASSERT.

### CODE REVIEW

**Comment by arturo182** [comment]
What is the issue though?

**Comment by kbeckmann** [comment]
.PLL.PLLM must be between 1 and 8. having it set to 0 leads to an assert in the hal. having it set to 1 should be fine as it acts as a divider and we just want to pass through.

**Comment by kbeckmann** [comment]
I guess the .ioc file should be updated with the correct clock config, can do that later.

**Comment by kbeckmann** [comment]
image

**Pull request merged**
